### ISSUE TITLE
add Merge Sort Algo in Java

### ISSUE THREAD

**Issue by Sofiyan-coder** [Ansh-Vikalp/Hacktoberfest2024-1#4]
Merge Sorting Algorithm implementation in Java

**Comment by Sofiyan-coder** [comment]
@Ansh-Vikalp  assign me this issue under Hacktobest 2024

**Comment by Ansh-Vikalp** [comment]
Hey @Sofiyan-coder I have forked this repo from @Vanshikapandey30 Which seems to be an excluded repo for Hacktoberfest. So it might happen that your contribution may not count. I am not sure, I am assigning this to. Firstly try to contribute and let me know is this repo is showing excluded or is valid. Check it on your https://hacktoberfest.com/profile/ after contribution.
